import { useEffect, useMemo, useState } from 'react';
import {
  Activity, ArrowRight, BookOpen, Check, CheckCircle2, ChevronDown, ChevronRight,
  CircleAlert, Download, ExternalLink, FileSearch, FileText, Gauge, Layers3,
  Library, Menu, MessageCircle, Network, Play, Quote, Route, Search, Send,
  ShieldCheck, Sparkles, Target, Users, X
} from 'lucide-react';

const API = '/api/index';
const DOCUMENTS = {
  textbook: { id: 'textbook', short: '学生教材', title: '义务教育教科书 语文 九年级上册', pages: 168, tone: 'orange', pdfUrl: '/materials/九年级语文上册-学生教材.pdf' },
  'teacher-guide': { id: 'teacher-guide', short: '教师教学用书', title: '教师教学用书 语文 九年级上册', pages: 612, tone: 'blue', pdfUrl: '/materials/九年级语文上册-教师教学用书.pdf' }
};
const ROUTES = [
  ['dashboard', '/', Gauge, '项目驾驶舱'],
  ['decision', '/decision/', Sparkles, '教学决策'],
  ['unit', '/unit/', Network, '单元导览'],
  ['cards', '/cards/', Layers3, '一课三卡'],
  ['evidence', '/evidence/', ShieldCheck, '证据图谱'],
  ['pitch', '/pitch/', Play, '方案路演'],
  ['library', '/library/', Library, '全文 Index'],
  ['ask', '/ask/', MessageCircle, '教材问答']
];
const EXAMPLES = [
  '《我爱这土地》第二节为什么不能删？怎样设计课堂活动？',
  '怎样指导学生读出《我爱这土地》的重音和节奏？',
  '“土地、河流、风、黎明”四个意象怎样组织成学习任务？',
  '第五单元议论性文章的学习任务有什么共同要求？'
];

async function request(path, options) {
  const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(options?.headers || {}) }, ...options });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || 'request_failed');
  return body;
}
function Logo() { return <div className="logo"><span className="logo-mark"><BookOpen size={21}/></span><span><b>活教参</b><small>AI 教学决策工作台</small></span></div>; }
function Badge({ children, tone = 'neutral' }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Stat({ icon: Icon, label, value, note, tone = '' }) { return <article className={`stat-card ${tone}`}><div className="stat-icon"><Icon/></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>; }
function SectionHead({ icon: Icon, eyebrow, title, note, action }) { return <div className="section-head"><div className="section-title"><span className="section-icon"><Icon/></span><div><small>{eyebrow}</small><h2>{title}</h2>{note && <p>{note}</p>}</div></div>{action}</div>; }
function routeId() { return document.body.dataset.route || 'dashboard'; }
function docName(id) { return DOCUMENTS[id]?.short || id; }

function Sidebar({ active, open, close }) {
  return <>{open && <button className="sidebar-scrim" aria-label="关闭导航" onClick={close}/>}<aside className={`sidebar ${open ? 'open' : ''}`}>
    <div className="sidebar-mobile-head"><Logo/><button onClick={close} aria-label="关闭导航"><X size={18}/></button></div><div className="desktop-logo"><Logo/></div>
    <div className="workspace-label">当前项目</div><a className="book-card" href="/unit/"><div className="book-cover">九上<br/><span>语文</span></div><div><strong>第一单元</strong><small>活动·探究 · 诗歌</small></div><ChevronRight size={16}/></a>
    <nav>{ROUTES.slice(0, 6).map(([id, href, Icon, label]) => <a key={id} href={href} className={active === id ? 'active' : ''} aria-current={active === id ? 'page' : undefined}><Icon size={18}/>{label}{id === 'cards' && <span className="nav-badge">3</span>}</a>)}</nav>
    <div className="source-stack"><div className="workspace-label">PAGEINDEX 文档空间</div>{Object.values(DOCUMENTS).map(item => <a className="source-dot" href={`/library/?doc=${item.id}`} key={item.id}><i className={item.tone}/><div><b>{item.short}</b><small>{item.pages} 页 · 已索引</small></div><CheckCircle2 size={14}/></a>)}</div>
    <div className="sidebar-tools"><a href="/library/" className={active === 'library' ? 'active' : ''}><Library/>全文 Index</a><a href="/ask/" className={active === 'ask' ? 'active' : ''}><MessageCircle/>教材问答</a></div>
    <div className="sidebar-foot"><ShieldCheck size={15}/><span>原文、综合建议与教师判断分层</span></div>
  </aside></>;
}
function Layout({ active, children }) {
  const [open, setOpen] = useState(false);
  const title = ROUTES.find(item => item[0] === active)?.[3] || '项目驾驶舱';
  return <div className="app-shell"><Sidebar active={active} open={open} close={() => setOpen(false)}/><main className="main-area"><header className="topbar"><div className="breadcrumb"><button className="mobile-menu" onClick={() => setOpen(true)}><Menu/></button><span>活教参 Demo</span><ChevronRight/><b>{title}</b></div><div className="top-actions"><span className="mode"><i/>证据优先模式</span><a href="/ask/"><MessageCircle/>提问</a><a href="/library/"><FileSearch/>索引</a></div></header><div className="content">{children}</div></main></div>;
}

function Dashboard() {
  return <div className="view-stack">
    <section className="hero dashboard-hero"><div><Badge tone="green"><Activity size={13}/> 可交互原型 · 全文索引已接通</Badge><h1>从 780 页权威材料，生成一节<br/><em>可追溯、可审核、可复用</em>的课</h1><p>不是让 AI 凭空写教案，而是先定位教材结构与教师用书依据，再把目标、活动、评价和引用组织成可修改的教学决策。</p><div className="hero-actions"><a className="primary" href="/ask/"><MessageCircle/>从一个问题开始</a><a href="/decision/"><Sparkles/>查看教学决策</a></div></div><div className="index-orbit"><div className="orbit-core"><FileSearch/><b>PageIndex</b><small>树结构索引</small></div>{['教材 168页','教参 612页'].map((x,i)=><span key={x} className={`orbit-node n${i+2}`}>{x}</span>)}</div></section>
    <div className="stats-grid"><Stat icon={FileText} label="已索引文档" value="2 份" note="学生教材 + 教师教学用书"/><Stat icon={Layers3} label="材料总页数" value="780 页" note="168 + 612" tone="blue"/><Stat icon={Network} label="结构化节点" value="单元—篇目—页面" note="支持目录树路由" tone="orange"/><Stat icon={CircleAlert} label="生成边界" value="三层标注" note="原文明示 / 系统综合 / 教师确认" tone="purple"/></div>
    <section className="panel"><SectionHead icon={Route} eyebrow="结构化检索" title="系统如何避免在 780 页里盲搜" note="检索过程在页面中可见，回答引用可直接打开对应 PDF 页。"/><div className="pipeline">{[['01','理解问题','识别篇目、任务、课型和产物'],['02','树路由','定位文档 → 单元 → 篇目 → 页面'],['03','页级取证','从候选页面抽取原文片段'],['04','组织回答','结论后绑定页码与原文引用']].map((item,i)=><div className="pipe-step" key={item[0]}><span>{item[0]}</span><div><b>{item[1]}</b><small>{item[2]}</small></div>{i<3&&<ArrowRight/>}</div>)}</div></section>
    <div className="two-col"><section className="panel corpus-panel"><SectionHead icon={BookOpen} eyebrow="知识底座" title="两份权威教学材料"/><div className="doc-list">{Object.values(DOCUMENTS).map(doc=><a className="doc-row" href={`/library/?doc=${doc.id}`} key={doc.id}><span className={`doc-icon ${doc.tone}`}><FileText/></span><div><Badge tone={doc.tone}>{doc.short}</Badge><b>{doc.title}</b><small>{doc.pages} 页 · 全文和目录结构已解析</small></div><CheckCircle2/></a>)}</div></section><section className="panel"><SectionHead icon={Target} eyebrow="教师工作流" title="从查资料到确认教学决策"/><div className="value-list">{[['定位','从目录树直接进入篇目和页码'],['比较','同时查看教材任务与教参建议'],['生成','形成目标、活动、问题和评价草案'],['审核','教师逐条确认依据、措辞与课堂适配']].map(([a,b])=><div key={a}><Check/><span><b>{a}</b><small>{b}</small></span></div>)}</div></section></div>
  </div>;
}

const claims = [
  ['教材任务结构','第一单元不是六篇课文的简单串联，而是“学习鉴赏—诗歌朗诵—尝试创作”的活动探究闭环。','学生教材 PDF 第7—8、20—26页'],
  ['篇目教学定位','《我爱这土地》需要把意象、时代背景、情感结构和朗读表现连接起来，而不是停留在意象释义。','教师教学用书 PDF 第51—57页'],
  ['课堂活动原则','先让学生回到原文定位，再通过删改比较、朗读试验和理由表达形成可观察的学习证据。','教师教学用书 PDF 第53、56页'],
  ['评价证据','评价不只看答案是否正确，还看学生能否引用诗句、说明推理过程并根据反馈修订表达。','教材任务与教参活动建议综合']
];
function Decision() {
  return <div className="view-stack"><section className="hero compact-hero"><div><Badge tone="green"><Sparkles/> 教学决策</Badge><h1>把材料依据翻译成<br/><em>可执行的 45 分钟课堂</em></h1><p>每个结论都标明来源和生成边界。教师可以继续追问，也可以打开原始 PDF 校验上下文。</p><div className="hero-actions"><a className="primary" href="/ask/?q=《我爱这土地》第二节为什么不能删？怎样设计课堂活动？"><MessageCircle/>用该问题生成</a><a href="/evidence/"><ShieldCheck/>查看证据关系</a></div></div><div className="decision-score"><span>当前示例</span><strong>《我爱这土地》</strong><small>第一单元 · 诗歌鉴赏与朗读</small></div></section>
    <section className="panel"><SectionHead icon={Target} eyebrow="决策摘要" title="四个需要教师确认的核心判断" note="文字来自两份材料的结构化检索与教学化重组，不替代教师专业判断。"/><div className="claims-grid">{claims.map(([title,text,source],i)=><article className={`claim ${i===3?'purple':i===1?'orange':'blue'}`} key={title}><div className="claim-top"><Badge tone={i===3?'purple':i===1?'orange':'blue'}>{i===3?'系统综合':'材料依据'}</Badge><a href="/library/"><ExternalLink/>校验</a></div><h3>{title}</h3><p>{text}</p><div className="evidence-links"><span>{source}</span></div></article>)}</div></section>
    <section className="panel"><SectionHead icon={Route} eyebrow="45 分钟流程" title="从初读感受走向有依据的表达"/><div className="lesson-timeline">{[['5分钟','声音入场','教师播放或示范两种不同语气的朗读，学生写下情感基调并圈出支持判断的词句。'],['10分钟','意象定位','小组把土地、河流、风、黎明对应的修饰语与动作整理成“意象—处境—情感”表。'],['12分钟','删改比较','尝试删去第二节或替换关键诗句，比较结构、视角和情感冲击发生了什么变化。'],['10分钟','朗读试验','依据理解标注重音、停连、节奏和语气；同伴只评价“处理是否有诗句依据”。'],['8分钟','迁移表达','用一段 100 字说明回答“为什么第二节不能删”，必须引用至少两处文本证据。']].map(([time,title,text],i)=><article key={title}><span>{i+1}</span><div><small>{time}</small><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
  </div>;
}
function Unit() { const tasks=[['01','学习鉴赏','教材 PDF 第7—19页','从基调、语言、意象和意境理解六篇诗歌，形成有依据的鉴赏表达。','7—8课时'],['02','诗歌朗诵','教材 PDF 第20—23页','把理解外化为重音、停连、节奏、语气和情感投入，并通过排练持续修订。','2—3课时'],['03','尝试创作','教材 PDF 第24—26页','观察生活、选择意象、借助联想与想象表达情感，在互评中修改作品。','2课时']]; return <div className="view-stack"><section className="hero compact-hero"><div><Badge tone="orange"><Network/> 第一单元 · 活动探究</Badge><h1>六篇诗歌不是六个孤立课时，<br/>而是一条输入—表现—迁移的学习路径</h1><p>单元导览把教材任务、篇目安排与教师用书建议并置，帮助教师先做整体设计，再进入单篇备课。</p></div><div className="unit-total"><span>3<small>项任务</small></span><i/><span>6<small>篇诗歌</small></span><i/><span>11—13<small>课时建议</small></span></div></section><section className="panel"><SectionHead icon={Route} eyebrow="任务闭环" title="学习鉴赏 → 诗歌朗诵 → 尝试创作"/><div className="task-flow">{tasks.map((t,i)=><article key={t[1]} className={i===1?'orange':i===2?'purple':'blue'}><div><span>{t[0]}</span><Badge tone={i===1?'orange':i===2?'purple':'blue'}>{t[4]}</Badge></div><h3>{t[1]}</h3><small>{t[2]}</small><p>{t[3]}</p>{i<2&&<ArrowRight className="task-arrow"/>}</article>)}</div></section><section className="panel"><SectionHead icon={BookOpen} eyebrow="篇目地图" title="第一单元六篇诗歌的教学入口"/><div className="lesson-grid">{[['沁园春·雪','意境、胸襟与词的节奏'],['周总理，你在哪里','呼告、反复与深情追寻'],['我爱这土地','意象群、时代语境与献身之情'],['乡愁','时间顺序、空间转换与核心意象'],['你是人间的四月天','色彩、声音与新诗形式'],['我看','自然意象、生命感悟与语言张力']].map(([a,b],i)=><a href={`/ask/?q=${encodeURIComponent(`怎样设计《${a}》的核心学习任务？`)}`} key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p><ArrowRight/></a>)}</div></section></div>; }
function Cards() { const cards=[['板书卡','意象—处境—情感—表达',['鸟：歌唱者 / 诗人自我投射','土地：苦难而深爱的祖国','河流、风：苦难与抗争的现实力量','黎明：希望与新生','第二节：由形象叙写转入直抒胸臆']],['提问卡','让问题把学生带回原文',['这只鸟为什么“嘶哑”而不是“清脆”？','四个意象的修饰语能否互换？','如果删去第二节，诗歌的结构和情感有何变化？','朗读时哪一处必须停顿？依据是什么？','怎样用一段话证明你的判断？']],['评价卡','用可观察证据判断学习发生',['能准确定位并引用关键诗句','能解释意象与时代语境的关系','朗读处理与文本理解一致','能回应同伴质疑并修订理由','能区分原文信息与个人推断']]]; return <div className="view-stack"><section className="hero compact-hero"><div><Badge tone="green"><Layers3/> 一课三卡</Badge><h1>把长篇教师用书压缩成<br/>上课真正会看的三张卡</h1><p>三张卡不是摘要，而是课堂执行界面：看什么、问什么、如何判断学生是否学会。</p></div><div className="card-stack-visual"><span>板书</span><span>提问</span><span>评价</span></div></section><div className="cards-view">{cards.map(([name,title,items],i)=><article className={`teach-card card-${i}`} key={name}><div className="teach-card-head"><span>0{i+1}</span><b>{name}</b><button><Download/></button></div><small className="card-purpose">《我爱这土地》示例</small><h3>{title}</h3><ul>{items.map(item=><li key={item}><CheckCircle2/>{item}</li>)}</ul><div className="review-stamp"><Users/>系统初稿 · 待教师确认</div></article>)}</div></div>; }
function Evidence() { return <div className="view-stack"><section className="hero compact-hero"><div><Badge tone="blue"><ShieldCheck/> 证据图谱</Badge><h1>证据不再藏在侧栏，<br/>而是跟着每个教学判断一起出现</h1><p>图谱的作用不是增加一个孤立功能，而是把“结论—依据—原页—教师确认”的关系讲清楚。点击节点可进入全文索引或原始 PDF。</p></div><div className="decision-score"><span>核心原则</span><strong>结论旁边见依据</strong><small>不要求用户切换上下文寻找证据</small></div></section><section className="panel"><SectionHead icon={Network} eyebrow="关系视图" title="《我爱这土地》教学决策的证据链"/><div className="evidence-flow"><div className="evidence-source"><a href="/document/?doc=textbook&page=14"><FileText/><b>学生教材 第14页</b><small>诗歌原文与旁批位置</small></a><a href="/document/?doc=teacher-guide&page=53"><FileText/><b>教师用书 第53页</b><small>课文研读与结构说明</small></a><a href="/document/?doc=teacher-guide&page=56"><FileText/><b>教师用书 第56页</b><small>问题设计与朗读活动</small></a></div><ArrowRight/><div className="evidence-center"><ShieldCheck/><b>证据绑定层</b><small>页码、章节、引文、关系类型</small></div><ArrowRight/><div className="evidence-output"><article><Badge tone="blue">原文明示</Badge><b>第二节承担情感直陈与结构收束</b></article><article><Badge tone="purple">系统综合</Badge><b>用删改比较让学生发现不可替代性</b></article><article><Badge tone="green">教师确认</Badge><b>根据班情决定朗读与写作产物</b></article></div></div></section><section className="panel"><SectionHead icon={Quote} eyebrow="审阅清单" title="每条教学建议至少回答四个问题"/><div className="value-list">{[['来自哪里','文档、章节、PDF 页码和原文片段是什么？'],['如何推导','是原文明示、跨页归纳，还是系统提出的课堂转化？'],['如何使用','对应哪一个教学环节、学生行为和学习产物？'],['谁来确认','哪些判断必须由教师根据学情、课时和课堂反馈调整？']].map(([a,b])=><div key={a}><Check/><span><b>{a}</b><small>{b}</small></span></div>)}</div></section></div>; }
function Pitch() { const steps=[['01','真实问题','教师需要跨 780 页材料定位依据，传统检索只能找到关键词，难以理解章节结构。'],['02','核心能力','以文档树作为路由层，以页级全文作为证据层，把搜索结果组织为可核验的教学决策。'],['03','产品路径','从问题进入，系统展示命中章节、引用页码、课堂转化和待教师确认项。'],['04','现场演示','询问“第二节为什么不能删”，打开教师用书第53、56页，再生成删改比较活动。'],['05','应用价值','缩短查找和重组时间，同时避免无依据生成；资产可复用为单元导览、一课三卡和教研材料。']]; return <div className="view-stack"><section className="hero compact-hero"><div><Badge tone="green"><Play/> 方案路演</Badge><h1>用三分钟讲清楚：<br/>为什么是活教参，而不是普通问答机器人</h1><p>本页只展示产品问题、技术路径和应用价值；内部项目要求不作为公开语料或网站内容。</p></div><div className="hero-actions"><a className="primary" href="/ask/?q=《我爱这土地》第二节为什么不能删？怎样设计课堂活动？"><Play/>进入现场问题</a></div></section><section className="panel"><SectionHead icon={Route} eyebrow="讲述结构" title="五步完成产品演示"/><div className="pitch-steps">{steps.map(([n,a,b])=><article key={n}><span>{n}</span><div><h3>{a}</h3><p>{b}</p></div></article>)}</div></section></div>; }

function Tree({ nodes, current, onPick }) {
  const [open,setOpen]=useState(new Set());
  useEffect(()=>{setOpen(new Set((nodes||[]).slice(0,2).filter(n=>n.children?.length).map(n=>n.id)));},[nodes]);
  const toggle=id=>setOpen(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});
  return <div className="index-tree">{(nodes||[]).map(node=><div key={node.id}><button className={current===node.id?'selected':''} onClick={()=>node.children?.length?toggle(node.id):onPick(node)}>{node.children?.length?(open.has(node.id)?<ChevronDown/>:<ChevronRight/>):<span/>}<b>{node.title}</b><small>{node.startPage}{node.endPage!==node.startPage?`—${node.endPage}`:''}</small></button>{Boolean(node.children?.length)&&open.has(node.id)&&<div className="index-tree-children"><Tree nodes={node.children} current={current} onPick={onPick}/></div>}</div>)}</div>;
}
function LibraryPage() {
  const initial = new URLSearchParams(location.search).get('doc') || 'teacher-guide';
  const [doc,setDoc]=useState(initial),[docs,setDocs]=useState([]),[tree,setTree]=useState([]),[page,setPage]=useState(null),[pageNo,setPageNo]=useState(initial==='textbook'?14:53),[query,setQuery]=useState('我爱这土地 第二节'),[results,setResults]=useState([]),[busy,setBusy]=useState(false),[selected,setSelected]=useState('');
  useEffect(()=>{request('/documents').then(x=>setDocs(x.documents||[])).catch(()=>{});},[]);
  useEffect(()=>{let cancelled=false;setTree([]);request(`/documents/${doc}/tree`).then(x=>{if(!cancelled)setTree(x.tree||x.nodes||[])}).catch(()=>{if(!cancelled)setTree([])});return()=>{cancelled=true};},[doc]);
  useEffect(()=>{let cancelled=false;setPage(null);request(`/documents/${doc}/pages/${pageNo}`).then(x=>{if(!cancelled)setPage(x.page||x)}).catch(()=>{if(!cancelled)setPage(null)});return()=>{cancelled=true};},[doc,pageNo]);
  const search=async e=>{e?.preventDefault();if(!query.trim())return;setBusy(true);try{const x=await request('/search',{method:'POST',body:JSON.stringify({query,scope:[doc],limit:10})});setResults(x.results||[]);}finally{setBusy(false)}};
  const switchDocument=id=>{setDoc(id);setPageNo(id==='textbook'?14:53);setSelected('');setResults([]);history.replaceState(null,'',`/library/?doc=${id}`)};
  const pick=node=>{setSelected(node.id);setPageNo(node.startPage)};
  return <div className="view-stack index-page"><section className="hero index-hero"><div><Badge tone="green"><Library/> 全文 Index</Badge><h1>像查目录一样理解结构，<br/>像翻书一样核对原页</h1><p>两个 PDF 已做页级全文解析与章节树索引。左侧选章节，中间读解析文本，右侧看搜索命中；原始 PDF 可随时打开。</p></div><div className="index-health"><b>780</b><span>页全文可检索</span><small>Provider 接口已预留，可切换自部署 PageIndex</small></div></section><div className="index-toolbar"><div>{docs.map(item=><button className={doc===item.id?'active':''} onClick={()=>switchDocument(item.id)} key={item.id}><i className={DOCUMENTS[item.id]?.tone}/><span><b>{docName(item.id)}</b><small>{item.pageCount} 页</small></span></button>)}</div><form onSubmit={search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索全文、篇目或教学问题"/><button disabled={busy}>{busy?'检索中':'检索'}</button></form></div><div className="index-workspace"><aside className="index-outline"><header><span>文档目录</span><small>结构化节点</small></header><Tree nodes={tree} current={selected} onPick={pick}/></aside><section className="index-reader"><header><div><Badge tone={DOCUMENTS[doc]?.tone}>{docName(doc)}</Badge><h2>{page?.title||'正在读取页面'}</h2><small>PDF 第 {pageNo} 页 {page?.printedPage?`· 书页 ${page.printedPage}`:''}</small></div><div><button disabled={pageNo<=1} onClick={()=>setPageNo(n=>n-1)}>上一页</button><input value={pageNo} onChange={e=>setPageNo(Math.max(1,Number(e.target.value)||1))}/><button onClick={()=>setPageNo(n=>n+1)}>下一页</button><a href={`/document/?doc=${doc}&page=${pageNo}`}><ExternalLink/>原始 PDF</a></div></header><article><div className="page-paper"><small>{docName(doc)} · PDF 第 {pageNo} 页</small>{String(page?.text||'页面解析内容加载中…').split(/\n+/).filter(Boolean).map((p,i)=>p.length<24?<h3 key={i}>{p}</h3>:<p key={i}>{p}</p>)}</div></article></section><aside className="index-results"><header><span>页级命中</span><small>{results.length?`${results.length} 条结果`:'输入关键词开始检索'}</small></header>{results.length===0?<div className="index-empty"><Search/><b>在当前文档中检索</b><p>搜索结果会显示章节、页码和原文片段，点击即可跳到对应页面。</p><button onClick={search}>搜索“{query}”</button></div>:results.map(r=><button key={`${r.documentId}-${r.pageNumber}-${r.nodeId}`} onClick={()=>{setDoc(r.documentId);setPageNo(r.pageNumber);setSelected(r.nodeId)}}><b>{r.title}</b><small>{docName(r.documentId)} · PDF 第{r.pageNumber}页</small><p>{r.quote}</p></button>)}</aside></div></div>;
}
function AskPage() {
  const params=new URLSearchParams(location.search); const [question,setQuestion]=useState(params.get('q')||EXAMPLES[0]),[answer,setAnswer]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const ask=async(e,q)=>{e?.preventDefault();const text=q||question;if(!text.trim()||busy)return;setQuestion(text);setBusy(true);setError('');try{setAnswer(await request('/ask',{method:'POST',body:JSON.stringify({question:text,scope:['textbook','teacher-guide'],limit:6})}));}catch(err){setError('暂时无法完成检索，请稍后重试。')}finally{setBusy(false)}};
  useEffect(()=>{if(params.get('q'))ask(null,params.get('q'));},[]);
  return <div className="view-stack ask-page"><section className="hero compact-hero"><div><Badge tone="green"><MessageCircle/> 教材问答</Badge><h1>先给依据，再给课堂建议</h1><p>回答仅使用公开的学生教材和教师教学用书。每段建议后都附页码、引文和原始 PDF 入口。</p></div><div className="decision-score"><span>当前检索范围</span><strong>2 份 · 780 页</strong><small>支持后续切换自部署 PageIndex Provider</small></div></section><div className="ask-layout"><section className="panel ask-main"><form className="ask-large" onSubmit={ask}><MessageCircle/><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="输入篇目、单元或教学问题…"/><button className="primary" disabled={busy||!question.trim()}><Send/>{busy?'正在取证':'开始提问'}</button></form>{error&&<div className="ask-error">{error}</div>}{busy&&<div className="answer-loading"><span/><span/><span/><p>正在 780 页材料中定位章节、读取页面并组织引用…</p></div>}{answer&&!busy&&<div className="answer-view"><div className="route-card"><b>检索路径</b><p>问题理解 → 章节路由 → 页级全文命中 → 引用绑定</p><span>{answer.provider==='pageindex'?'PageIndex Provider':'本地全文索引'} · 命中 {answer.route?.resultCount||0} 页</span></div><div className="question-bubble"><small>你的问题</small><p>{answer.question}</p></div>{answer.sections?.map((section,i)=><article className="answer-section" key={i}><Badge tone={i===0?'green':'blue'}>{section.title}</Badge><p>{section.text}</p><div className="citation-list">{section.citations?.map((c,j)=><a href={`/document/?doc=${c.documentId}&page=${c.pageNumber}`} key={`${c.documentId}-${c.pageNumber}-${j}`}><span>{j+1}</span><div><b>{docName(c.documentId)} · PDF 第{c.pageNumber}页</b><p>{c.quote}</p></div><ExternalLink/></a>)}</div></article>)}</div>}</section><aside className="panel ask-side"><SectionHead icon={Sparkles} eyebrow="示例问题" title="从真实备课任务开始"/><div className="ask-suggestions">{EXAMPLES.map(q=><button onClick={()=>ask(null,q)} key={q}>{q}<ArrowRight/></button>)}</div><div className="ask-principles"><b>回答边界</b><p>原文事实直接引用；教学活动是基于材料的系统综合；课时、学情和评价标准由教师最终确认。</p></div></aside></div></div>;
}
function DocumentPage() { const params=new URLSearchParams(location.search),doc=params.get('doc')||'teacher-guide',page=Math.max(1,Number(params.get('page'))||1),info=DOCUMENTS[doc]||DOCUMENTS['teacher-guide']; return <div className="view-stack document-page"><section className="panel document-head"><div><Badge tone={info.tone}>{info.short}</Badge><h1>{info.title}</h1><p>当前打开 PDF 第 {page} 页。使用浏览器内置工具可缩放、搜索、下载或打印。</p></div><div><a href={`/library/?doc=${doc}`}><ArrowRight/>返回全文 Index</a><a className="primary" href={info.pdfUrl} target="_blank" rel="noreferrer"><ExternalLink/>新窗口打开</a></div></section><iframe title={`${info.short} PDF`} src={`${info.pdfUrl}#page=${page}&view=FitH`} /></div>; }
function App(){const active=routeId();let page=<Dashboard/>;if(active==='decision')page=<Decision/>;if(active==='unit')page=<Unit/>;if(active==='cards')page=<Cards/>;if(active==='evidence')page=<Evidence/>;if(active==='pitch')page=<Pitch/>;if(active==='library')page=<LibraryPage/>;if(active==='ask')page=<AskPage/>;if(active==='document')page=<DocumentPage/>;return <Layout active={active}>{page}</Layout>}
export default App;
