// Teacher-facing language lives here so error, empty, and loading states do not
// drift back into infrastructure terminology as the product grows.
export const UI_COPY = Object.freeze({
  provider: {
    systemGateway: '系统智能（默认）',
    personalKey: '我的智能连接',
    stableSnapshot: '已核验教材固定版'
  },
  ask: {
    loading: '正在锁定篇目与页段，核对课程标准、学生教材和教师用书；初稿完成后还会做一次教材依据与课堂可用性校核…',
    ready: '三类教学材料和系统智能服务已准备好。输入篇目或课堂问题，先找可核验依据，再组织课堂方案。',
    personalReady: '我的智能连接 连接已准备好。系统会沿用当前篇目和材料范围，并把引用重新绑定到真实 PDF 页面。',
    loginReady: '三类教学材料和系统智能服务已准备好。登录后可以连续提问、保存方案并在下次备课时继续编辑。',
    noProvider: '当前没有可用的 AI 服务，请稍后重试或联系部署人员。',
    title: '先把这节课讲清楚，',
    subtitle: '再让每个判断回到教材原页',
    description: '先固定篇目，再分别核对课程标准的学段要求、教师用书的教学建议和学生教材的原文任务。教师可以连续追问，再把已核验依据转成课时流程、问题链、评价和三张课堂卡。',
    blockedTitle: '当前教材依据还不够完整',
    blockedBody: '为避免把推测当成教材结论，本次只保留可核验内容。请补充篇名、章节或关键词，或切换到“学生教材与教师用书”范围后再试。'
  },
  errors: {
    ai_checking: '正在检查 AI 服务，请稍候再开始提问。',
    auth_required: '登录后才能生成备课方案，请先登录。',
    auth_invalid: '登录已过期，请重新登录后继续。',
    auth_rate_limited: '验证请求过于频繁，请稍后再试。',
    user_already_exists: '该邮箱已注册，请直接登录。',
    email_not_confirmed: '邮箱还没有完成验证，请先点击验证邮件。',
    weak_password: '密码强度不足，请使用至少 8 位密码。',
    auth_not_configured: '账号服务尚未配置，请联系部署人员。',
    key_not_found: '当前没有可用的智能生成服务。请稍后重试，或在“AI 设置”中添加并测试我的智能连接配置。',
    key_invalid: '请输入有效的智能连接信息。',
    deepseek_unauthorized: '我的智能连接配置无效，请重新测试或更换。',
    deepseek_forbidden: '我的智能连接未获授权，请检查账号权限。',
    deepseek_rate_limited: '我的智能连接 请求过于频繁，请稍后重试。',
    deepseek_timeout: '我的智能连接 响应超时，请稍后重试。',
    deepseek_unavailable: '我的智能连接 暂时不可用，请稍后重试。',
    deepseek_invalid_response: '我的智能连接 返回内容无法解析，请重试。',
    deepseek_invalid_request: '我的智能连接 请求参数无效，请检查模型设置。',
    deepseek_request_failed: '我的智能连接 连接失败。系统 AI 仍可使用，请切换为“系统智能（默认）”后重试。',
    gateway_not_configured: '系统 AI 尚未配置，暂时无法生成方案，请联系部署人员。',
    gateway_invalid_url: '系统 AI 地址无效，暂时无法生成方案，请联系部署人员。',
    gateway_unauthorized: '系统 AI 的连接凭据暂时不可用。当前定稿和已保存内容都已保留，请稍后重试生成。',
    gateway_forbidden: '系统 AI 暂时拒绝了请求，请稍后重试。',
    gateway_rate_limited: '系统 AI 当前使用人数较多。定稿内容已经保留，请稍后重试。',
    gateway_timeout: '系统 AI 本次处理时间较长，未覆盖原有内容。请直接重试生成。',
    gateway_unavailable: '系统 AI 暂时没有完成生成。定稿内容已经保留，请稍后重试。',
    gateway_invalid_response: '系统 AI 返回内容暂时无法读取，请重试。',
    gateway_request_failed: '系统 AI 暂时没有完成请求，请稍后重试。',
    pageindex_not_configured: '教材目录尚未准备好，暂时无法生成方案，请检查教材处理状态。',
    pageindex_unavailable: '教材目录暂时没有响应，未生成方案，请稍后重试。',
    pageindex_timeout: '教材目录读取超时，未生成方案，请稍后重试。',
    pageindex_unauthorized: '教材目录连接未通过验证，请联系部署人员检查配置。',
    pageindex_forbidden: '教材目录暂时拒绝了请求，请稍后重试。',
    pageindex_rate_limited: '教材目录请求过于频繁，请稍后再试。',
    pageindex_invalid_request: '教材目录暂时无法处理这个问题，请换一种问法再试。',
    pageindex_invalid_response: '教材目录返回内容暂时无法读取，请稍后重试。',
    pageindex_request_failed: '教材目录暂时没有响应，未生成方案，请稍后重试。',
    pageindex_not_found: '暂时找不到这份教材，请返回教材库重新选择。',
    pageindex_method_not_allowed: '教材目录请求没有完成，请稍后重试。',
    index_provider_error: '教材目录暂时没有响应，未生成方案，请稍后重试。',
    evidence_insufficient: '当前依据不足，未覆盖原有内容。请扩大教材范围或调整问题后重试。',
    card_generation_failed: '生成结果还没有达到课堂可用要求，因此没有覆盖原有内容。请重试，或回到定稿台补充教学重点。',
    card_locked: '这张卡已经锁定，如需调整请先回到备课问答生成新的方案。',
    card_not_found: '暂时找不到这张课堂卡，请刷新后重试。',
    edit_conflict: '这份方案刚刚在别处更新过，请刷新后再保存，避免覆盖最新内容。',
    target_class_required: '请先填写目标班级，再建立新的教学版本。',
    target_class_same: '目标班级与当前方案相同，不需要另建版本。',
    classroom_run_confirmed: '这份课堂记录已经由教师确认。如需再次授课，请复制方案后建立新的课堂记录。',
    learning_evidence_questions_required: '当前方案还没有可回流的问题。请先生成提问卡或完成问题链预演。',
    learning_evidence_confirmed: '这份学情回流已经由教师确认。如需重新记录，请复制方案后开始新一轮。',
    learning_evidence_not_found: '还没有建立本课的学情回流记录。',
    learning_evidence_stale: '提问卡已经更新，请按最新问题重新整理学情回流。',
    learning_evidence_incomplete: '请至少完整记录一道题的提交人数和达成分布。',
    learning_evidence_counts_invalid: '人数没有对齐：三种达成情况之和应等于提交人数，提交人数不能超过布置人数。',
    student_sample_contains_contact: '请删除手机号、邮箱或学号，只保留班级层面的归纳。',
    citation_outside_lesson: '有教材依据不属于当前篇目，请重新搜索后再保存。',
    citation_document_forbidden: '有教材依据不属于当前账号或公共教材，请重新搜索后再保存。',
    citation_text_mismatch: '教材摘录与原始页面不一致，未保存。请重新打开该页核验。',
    lesson_change_requires_new_draft: '这份方案已有锁定卡片。请新建备课，再切换篇目。',
    deliberation_confirmed: '这份备课取舍已经确认。如需调整，请先更新方案，再重新比较。',
    deliberation_not_found: '还没有生成本课的备课取舍。',
    deliberation_stale: '方案或教材依据已经变化，请按最新内容重新比较。',
    deliberation_incomplete: '请为每个关键取舍选择一条课堂路径。',
    deliberation_invalid_response: '这次比较没有形成可用结果，请重新比较。',
    plan_confirmation_required: '这份方案还没有完成教师定稿，或定稿后又有修改。请先回到课堂设计确认本版，再收进教研资产库。',
    share_not_found: '这份共备链接已失效、已到期或已被发布者撤销。',
    share_token_invalid: '共备链接不完整，请让发布者重新复制。',
    share_service_not_configured: '共备服务尚未完成生产配置，暂时不能打开链接。',
    share_public_evidence_required: '当前方案只引用了私人材料，暂不能发布为公开共备快照。',
    share_cards_required: '这份方案还没有生成可分享的课堂卡。请先完成一课三卡。',
    question_required: '请告诉我篇目、单元或想解决的课堂问题。',
    query_required: '请输入篇名、章节、关键词或教学问题。'
  },
  recovery: {
    title: '教材目录暂时没有响应',
    body: '你的问题已经保留。刚才读取教材时出现波动，可以再次尝试，或先查看教材处理状态。',
    retry: '重试',
    switchBook: '换一本教材',
    status: '查看教材处理状态',
    snapshot: '使用已核验教材固定版',
    snapshotBanner: '当前使用：已核验教材固定版',
    snapshotBody: '答案仍可打开原始教材核验，但可能不含最近的教材更新。'
  }
});

export function errorCopy(error) {
  const code = String(error?.code || error?.message || '').trim();
  return UI_COPY.errors[code] || '本次请求没有完成，请稍后重试。';
}
